name: Sign Release and Build Linux Binary

on:
  workflow_dispatch:

jobs:
  build-linux:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build linux binary
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential
          g++ -o ./visual\ studio/Resource\ Files/Suspend_Input_Helper_Linux_Binary ./visual\ studio/Resource\ Files/Suspend_Input_Helper_Source/linux_helper.cpp -O3 -std=c++11

      - name: Upload linux binary
        uses: actions/upload-artifact@v4
        with:
          path: visual\ studio/Resource\ Files/Suspend_Input_Helper_Linux_Binary
          name: Suspend_Input_Helper_Linux_Binary
      
      - name: Commit and push linux binary to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add "visual studio/Resource Files/Suspend_Input_Helper_Linux_Binary"
          if git diff --cached --quiet; then
            echo "Nothing to commit"
          else
            git commit -m "Update linux binary"
            git push
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  
  sign:
    needs: build-linux # Ensure linux build completes first
    runs-on: windows-latest
    
    permissions:
      contents: write

    env:
      SIGNPATH_API_TOKEN: ${{ secrets.SIGNPATH_API_TOKEN }}
      SIGNPATH_ORGANIZATION_ID: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
      SIGNPATH_PROJECT_SLUG: ${{ secrets.SIGNPATH_PROJECT_SLUG }}
      SIGNPATH_SIGNING_POLICY: ${{ secrets.SIGNPATH_SIGNING_POLICY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build project
        run: msbuild "visual studio\suspend.sln" /p:Configuration=Release /p:Platform=x64 /p:ClCompileOptimization=MaxSpeed

      - name: Upload unsigned ZIP for signing
        id: upload-artifact-step
        uses: actions/upload-artifact@v4
        with:
          path: visual studio\x64\Release\suspend.exe

      - name: Submit signing request to SignPath and upload to signed
        uses: signpath/github-action-submit-signing-request@v1.1
        with:
          organization-id: ${{ secrets.SIGNPATH_ORGANIZATION_ID }}
          project-slug: ${{ secrets.SIGNPATH_PROJECT_SLUG }}
          signing-policy-slug: ${{ secrets.SIGNPATH_SIGNING_POLICY }}
          api-token: ${{ secrets.SIGNPATH_API_TOKEN }}
          github-artifact-id: ${{ steps.upload-artifact-step.outputs.artifact-id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          wait-for-completion: true
          artifact-configuration-slug: initial
          output-artifact-directory: signed/

      - name: Prepare zip staging folder
        run: |
          mkdir staging
          copy "signed\suspend.exe" staging\
          copy "README.md" staging\
        shell: pwsh
      
      - name: Create zip (store mode, flat structure)
        run: 7z a -mx=0 Spencer-Macro-Utilities.zip suspend.exe README.md
        working-directory: staging
      
      - name: Move zip to signed/ (overwrite)
        run: Move-Item staging\Spencer-Macro-Utilities.zip signed\ -Force
        shell: pwsh

      - name: Clean up staging folder
        run: Remove-Item -Recurse -Force staging
        shell: pwsh

      - name: Pull latest changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git pull origin ${{ github.ref }}

      - name: Commit and push signed executable to repo
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add signed/Spencer-Macro-Utilities.zip
          git commit -m "Update signed executable"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
